[package]
name = "solana-spammer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.16" # or latest
solana-sdk = "1.16" # or latest
tokio = { version = "1", features = ["full"] }
rand = "0.8"
dotenv = "0.15.0"